export const Terminos_Y_Condiciones =`
Combo Dominos Fuego Original grande + Papotas\n
Operadora y Procesadora de Productos de Panificación, S.A. de C.V., en Av. Revolución 1267 piso 21, Col. Alpes, Álvaro Obregón, CDMX, C.P. 01040; te ofrece: Combo Pizza grande (35 cm) masa Original mitad Pepperoni mitad Hawaiana con salsa Dominos Fuego + Papotas Dominos Fuego (220 g) por $249 al ordenar en mostrador, por teléfono, en línea y por la App. Vigencia del 07 de febrero al 30 de junio de 2024. No acumulable con otras promociones, cupones ni descuentos. Válido en todas las tiendas Dominos Pizza de la República Mexicana al ordenar en mostrador, en línea, por teléfono o por la App. Sujeto a disponibilidad de producto en tienda. Aplica únicamente en las pizzas señaladas, no aplica en otros tamaños, ni tipos de pizza, ni masas no mencionadas. **Monto mínimo de orden para servicio a domicilio de $149. Consulta www.dominos.com.mx. Precios en MXN. Nuestros precios incluyen IVA. HAZ EJERCICIO.

Combo Dominos Fuego Original grande + Alitas o Boneless

Operadora y Procesadora de Productos de Panificación, S.A. de C.V. en Av. Revolución 1267 piso 21, Col. Alpes, Álvaro Obregón, CDMX, C.P. 01040; y subfranquicias te ofrece: Combo Pizza grande (35 cm) masa Original mitad Pepperoni mitad Hawaiana con salsa Dominos Fuego + Alitas (230 g) o Boneless (200 g) Dominos Fuego por $299 pesos al ordenar en mostrador y por $319 pesos al ordenar por servicio a domicilio (teléfono, sitio web o App). Vigencia del 07 de febrero al 30 de junio de 2024. Válido en todas las tiendas Dominos Pizza de la República Mexicana al ordenar en mostrador, por teléfono, en línea o por la App. Sujeto a disponibilidad de producto en tienda. Aplica únicamente en el tipo de pizza señalada, no aplica en otros tamaños, ni tipos de pizza, ni masas no mencionadas. Monto mínimo de orden para servicio a domicilio de $149. Precios en MXN. Nuestros precios incluyen IVA. HAZ EJERCICIO.

Combo Dominos Fuego Papotas + Alitas o Boneless

Operadora y Procesadora de Productos de Panificación, S.A. de C.V., en Av. Revolución 1267 piso 21, Col. Alpes, Álvaro Obregón, CDMX, C.P. 01040 y subfranquicias te ofrecen: Papotas Dominos Fuego (220 g) + Alitas (230 g) o Boneless (200 g) Dominos Fuego por $169. Vigencia 07 de febrero al 30 de junio de 2024. No acumulable con otras promociones, cupones, ni descuentos. Válido en todas las tiendas Dominos Pizza de la República Mexicana al ordenar en mostrador, por teléfono, en línea o por la App. Sujeto a disponibilidad de producto en tienda. Aplica únicamente en los adicionales señalados, no aplica en otros productos no mencionados. **Monto mínimo de orden para servicio a domicilio de $149. Precios en MXN. Nuestros precios incluyen IVA. HAZ EJERCICIO.

Cups 2x$30

Operadora y Procesadora de Productos de Panificación, S.A. de C.V., en Av. Revolución 1267 piso 21, Col. Alpes, Álvaro Obregón, CDMX, C.P. 01040 y subfranquicias te ofrecen: 2 Cups de salsas* a elegir por $30 pesos. *Salsas: Marinara (56g), Salcidita (56g), BBQ (56g), Cheesepeño (56g), Ranch (56g), Mango Habanero (56g) y Brava (56g). Vigencia del 01 de enero al 30 de abril de 2024. Promoción válida al ordenar dos Cups de salsas. Válido en todas las tiendas Dominos Pizza de la República Mexicana al ordenar en mostrador, por teléfono, en línea o por la App. Sujeto a disponibilidad de producto en tienda. Aplica únicamente en los cups de salsas señalados, no aplica en otros productos no mencionados. **Monto mínimo de orden para servicio a domicilio de $149. Precios en MXN. Nuestros precios incluyen IVA. HAZ EJERCICIO.

Adicionales 2x$99

Operadora y Procesadora de Productos de Panificación, S.A. de C.V., en Av. Revolución 1267 piso 21, Col. Alpes, Álvaro Obregón, CDMX, C.P. 01040 y subfranquicias te ofrecen: 2 adicionales participantes* a elegir, por $99. Vigencia del 01 de enero al 30 de abril de 2024. El precio aplica al ordenar dos adicionales participantes. *Adicionales participantes: Cajeta Baitz (16 Piezas), Canela Baitz (16 piezas), Papotas (220 g), 1 refresco (Pepsi, Manzanita, Mirinda o 7Up) (1.5 litros en tiendas delivery o 2 refrescos de 600 mL o 2 vasos de 650 mL en tiendas express). No acumulable con otras promociones, cupones ni descuentos. Válido en todas las tiendas Dominos Pizza de la República Mexicana al ordenar en mostrador, por teléfono, en línea o por la App. Sujeto a disponibilidad de producto en tienda. Aplica únicamente en los adicionales señalados, no aplica en otros productos no mencionados. **Monto mínimo de orden para servicio a domicilio de $149. Precios en MXN. Nuestros precios incluyen IVA. HAZ EJERCICIO.`;